import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/icon.css";

import { BlogHeader } from "@/components/features/Header";
import { BlogFooter } from "@/components/features/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[url(/img/background.png)] bg-fixed h-[2000px]">
        <BlogHeader />
        <main className="mx-auto max-w-content">{children}</main>
        <BlogFooter />
      </body>
    </html>
  );
}
